In [1]:
import pandas as pd
import numpy as np

In [2]:
outcomes_df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-09/wwc_outcomes.csv")
squads_df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-09/squads.csv")
codes_df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-09/codes.csv")

In [3]:
outcomes_df = pd.merge(left=outcomes_df, right=codes_df, how="left")

In [4]:
squads_df.head()

,squad_no,country,pos,player,dob,age,caps,goals,club
0,1,US,GK,Alyssa Naeher,1988-04-20T00:00:00Z,31,43.0,0.0,Chicago Red Stars
1,2,US,FW,Mallory Pugh,1998-04-29T00:00:00Z,21,50.0,15.0,Washington Spirit
2,3,US,MF,Sam Mewis,1992-10-09T00:00:00Z,26,47.0,9.0,North Carolina Courage
3,4,US,DF,Becky Sauerbrunn,1985-06-06T00:00:00Z,34,155.0,0.0,Utah Royals
4,5,US,DF,Kelley O'Hara,1988-08-04T00:00:00Z,30,115.0,2.0,Utah Royals

In [16]:
codes_df.shape

(212, 2)

In [15]:
outcomes_df.head(60)

,year,team,score,round,yearly_game_id,team_num,win_status,country
0,1991,CHN,4,Group,1,1,Won,China PR
1,1991,NOR,0,Group,1,2,Lost,Norway
2,1991,DEN,3,Group,2,1,Won,Denmark
3,1991,NZL,0,Group,2,2,Lost,New Zealand
4,1991,JPN,0,Group,3,1,Lost,Japan
5,1991,BRA,1,Group,3,2,Won,Brazil
6,1991,GER,4,Group,4,1,Won,Germany
7,1991,NGA,0,Group,4,2,Lost,Nigeria
8,1991,SWE,2,Group,5,1,Lost,Sweden
9,1991,USA,3,Group,5,2,Won,United States
10,1991,TPE,0,Group,6,1,Lost,Chinese Taipei
11,1991,ITA,5,Group,6,2,Won,Italy
12,1991,NOR,4,Group,7,1,Won,Norway
13,1991,NZL,0,Group,7,2,Lost,New Zealand
14,1991,CHN,2,Group,8,1,Tie,China PR
15,1991,DEN,2,Group,8,2,Tie,Denmark
16,1991,JPN,0,Group,9,1,Lost,Japan
17,1991,SWE,8,Group,9,2,Won,Sweden
18,1991,ITA,1,Group,10,1,Won,Italy
19,1991,NGA,0,Group,10,2,Lost,Nigeria
20,1991,BRA,0,Group,11,1,Lost,Brazil
21,1991,USA,5,Group,11,2,Won,United States
22,1991,TPE,0,Group,12,1,Lost,Chinese Taipei
23,1991,GER,3,Group,12,2,Won,Germany
24,1991,JPN,0,Group,13,1,Lost,Japan
25,1991,USA,3,Group,13,2,Won,United States
26,1991,CHN,4,Group,14,1,Won,China PR
27,1991,NZL,1,Group,14,2,Lost,New Zealand
28,1991,BRA,0,Group,15,1,Lost,Brazil
29,1991,SWE,2,Group,15,2,Won,Sweden
30,1991,NOR,2,Group,16,1,Won,Norway
31,1991,DEN,1,Group,16,2,Lost,Denmark
32,1991,TPE,2,Group,17,1,Won,Chinese Taipei
33,1991,NGA,0,Group,17,2,Lost,Nigeria
34,1991,ITA,0,Group,18,1,Lost,Italy
35,1991,GER,1,Group,18,2,Won,Germany
36,1991,CHN,0,Quarter Final,19,1,Lost,China PR
37,1991,SWE,1,Quarter Final,19,2,Won,Sweden
38,1991,USA,7,Quarter Final,20,1,Won,United States
39,1991,TPE,0,Quarter Final,20,2,Lost,Chinese Taipei
40,1991,DEN,1,Quarter Final,21,1,Lost,Denmark
41,1991,GER,2,Quarter Final,21,2,Won,Germany
42,1991,NOR,3,Quarter Final,22,1,Won,Norway
43,1991,ITA,2,Quarter Final,22,2,Lost,Italy
44,1991,GER,2,Semi Final,23,1,Lost,Germany
45,1991,USA,5,Semi Final,23,2,Won,United States
46,1991,SWE,1,Semi Final,24,1,Lost,Sweden
47,1991,NOR,4,Semi Final,24,2,Won,Norway
48,1991,SWE,4,Third Place Playoff,25,1,Won,Sweden
49,1991,GER,0,Third Place Playoff,25,2,Lost,Germany
50,1991,NOR,1,Final,26,1,Lost,Norway
51,1991,USA,2,Final,26,2,Won,United States
52,1995,GER,1,Group,1,1,Won,Germany
53,1995,JPN,0,Group,1,2,Lost,Japan
54,1995,SWE,0,Group,2,1,Lost,Sweden
55,1995,BRA,1,Group,2,2,Won,Brazil
56,1995,NOR,8,Group,3,1,Won,Norway
57,1995,NGA,0,Group,3,2,Lost,Nigeria
58,1995,ENG,3,Group,4,1,Won,England
59,1995,CAN,2,Group,4,2,Lost,Canada